# Generated by Django 3.2.4 on 2021-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_name',
            field=models.CharField(default='wwwe', max_length=20),
            preserve_default=False,
        ),
    ]
